apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app: hello
        app.kubernetes.io/name: hello
    spec:
      serviceAccountName: hello
      containers:
      - name: hello
        image: dgeorgievski/dgeorgievski-hello:0.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"  
            cpu: "200m"       
          requests:
            memory: "128Mi"  
            cpu: "100m"      
