name: devbox

on: 
  push:
    branches:
      - devbox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run arbitrary commands
        run: devbox run -- echo "done!"

      - name: Conventional Check of last commit
        run: |
          devbox run ccheck
          