# .github/workflows/release.yml
name: semantic release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  # issues: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Run GoReleaser
        uses: go-semantic-release/action@v1
        with:
          # hooks: goreleaser
          changelog-generator-opt: "emojis=true"
        env:
          GITHUB_TOKEN: ${{ secrets.HELLO_TOKEN }}
