# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      release_bump:
        description: Select part of SemVer to increment. Overriden by version_override value if provided. 
        default: Patch
        type: choice
        options:
          - Major
          - Minor
          - Patch 
      version_override:
        description: Set version manually. If provided, it overrides the application version.
        type: string

  # workflow_run:
  #   workflows: [build]
  #   types: [completed]

permissions:
  contents: write
  packages: write
  # issues: write
  id-token: write

jobs:
  goreleaser:
    ## if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HELLO_TOKEN }}
